"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _case_studies from './case-studies.bones.json'
import _contact from './contact.bones.json'
import _journal from './journal.bones.json'
import _processes from './processes.bones.json'
import _skills from './skills.bones.json'

registerBones({
  "case-studies": _case_studies,
  "contact": _contact,
  "journal": _journal,
  "processes": _processes,
  "skills": _skills,
})
